### ISSUE TITLE
Broaden the CoC policy scope? Or be more explicit in CoC about community as a whole

### ISSUE THREAD

**Issue by yo-bj** [code4lib/code-of-conduct#46]
Starter stub... see https://listserv.nd.edu/cgi-bin/wa?A2=code4lib;970bebea.1407 and subsequent thread for initial question and discussion.

**Comment by phette23** [comment]
Superceded by other issue, see Becky's reference. The CoC is now broader in scope than the conference. This conversation predates the creation of the Community Support Squad and many of our CoC procedures.
