### ISSUE TITLE
CoC outside the conference - online spaces 

### ISSUE THREAD

**Issue by yo-bj** [code4lib/code-of-conduct#66]
Branching off of #46 since 1) old thread is old and 2) the link in the original issue post is now dead, and I need to find the thread in the new mail archive.

Since the CoC is still primarily focused on implementation in a conference/event setting, I'm wondering if one way we can "expand" the CoC is by adopting a list of explicit social norms. For example, Write The Docs has a list of community conduct expectations for their very active Slack channel. The [Social Rules](https://github.com/writethedocs/www/blob/master/docs/slack.rst) were inspired by the [Recurse Center](https://www.recurse.com/manual#sub-sec-social-rules). The Social Rules does not replace the WTD CoC but compliments it.

Enforcement of these rules in the WTD Slack, from my observations, has been mostly peer to peer, with the occasional reminder from one of the WTD organizers. The [reporting ](https://github.com/writethedocs/www/blob/master/docs/code-of-conduct-reporting.rst)and [response ](https://github.com/writethedocs/www/blob/master/docs/code-of-conduct-response.rst)processes of the Social Rules are included in the main WTD policies.

The adoption of any type of guidelines/expectations/etc. would require the community to revisit the conversation in #46 about setting up a reporting and response structure outside conferences and events. Some of the logistics could be offset with our relationship with DLF with regard to reporting mechanisms or a few staff to help with reports and responses. We also have a few years of Duty Officers under our belts, and the selection, training, and reporting processes developed for the DOs could be used to help with implementation and maintenance of such a reporting/response structure.

I can create a new PR with some variation of the WTD Slack Social Rules, but the issue of reporting and response structures outside events needs to be addressed in that PR as well. Thoughts and suggestions about how to go about that are welcome, as well as about the adoption of additional conduct guidelines in the community.

**Comment by anarchivist** [comment]
I think this is a great idea. I'm not sure we can necessarily expect DLF to take this on as a staff responsibility (i.e., beyond the mailing list) but it would be good to have a conversation about that. 

The thread I think you're looking for: https://lists.clir.org/cgi-bin/wa?A1=ind1407&L=CODE4LIB#24 

I also wonder what our approach for discussing and finalizing the social rules should be

One specific area that's neither specifically reporting nor response is ensuring that some set of folks has ops for the channel (especially given the IRC spamming on Christmas Day).

**Comment by yo-bj** [comment]
Thanks for digging up the thread, @anarchivist 👍 

I saw the archived IRC log with the spam, and agree that in the shorter term we need to expand the number of folks who have ops.

One suggestion about how to approach a community discussion is a breakout at the conference, which I can volunteer ~~as tribute~~ to help facilitate. This could be complimented by online discussions through the listserv and Slack:

- Slack: to help with keeping the discussion on topic and focused, we can create a new channel dedicated to feedback and amending the CoC.
- Listserv: Do we want to write a summary email, and point folks to the various forums for discussion (aka here and dedicated Slack channel)? I'm thinking of past discussions on the listserv around the CoC and how they tend to veer off-track in a listserv setting. Or perhaps we again embrace the listserv chaos...

Trying to formalize the CoC with the supporters/abstainers/objectors documents didn't really catch on. The diebolt-a-tron or some other version of it could be an option, though we will have similar concerns expressed by the community regarding "who should vote" and if a vote is binding or not.

**Comment by sdellis** [comment]
It looks like the current CoC covers online conduct, but perhaps does not provide authority to any group to enforce it outside of the conference? Is that the key question here that needs to be discussed?

**Comment by yo-bj** [comment]
That's one of the key questions that need to be discussed, yes. The CoC documents have a reporting structure for conferences, but there is really no reporting structure in the community itself, outside of the conference. We have @helpers in IRC and the listserv admin, and that's pretty much it. We need to look at a structure for recruitment, reporting, enforcement, and cycling out of the enforcement/reporting role.

The other part of the discussion is expanding the CoC to be explicit in calling out social norms in community spaces. The CoC as it stands is a good foundation, and additions like something akin to the Social Rules are meant to be built off of that foundation. We have an earlier document about how to act in code4lib spaces in the wiki, and we have been pointing folks to that document for years. If we're pointing people to a document that gives them social norm expectations, then it's an important enough document to consider for inclusion in the CoC repo.

(The PR I have in mind combines that wiki page with some of the Social Rules linked in the first post.)

**Comment by sdellis** [comment]
Ok, that all sounds good! I like the idea of having both CoC and a Social Rules documents be prominent in all contexts (IRL and online). I am wary of conflating them too much though. The CoC is behavior that is strictly not tolerated, while the other simply tries to avoid annoying or counter-productive behavior. Responses and consequences should be very different for each.

I also have to admit that I find the title "Social Rules" to be a bit off-putting. IMHO "Community Expectations", "Social Etiquette", "Community Best Practices" ... or simply keeping the title "How to Hack Code4Lib" might be better.

**Comment by yo-bj** [comment]
The name can definitely be changed from Rules, though I'd like to see if we can come up with a better alternative to "hack". And you are right that there will probably be some differences in responses for each document if folks don't follow one or the other, though we'd should probably reserve the right to escalate to the CoC response if the counter-productive behavior is disruptive to the point of harming or endangering someone(s).

**Comment by sdellis** [comment]
👍  to all that!

**Comment by yo-bj** [comment]
There is a gist that is a major version update to "How to hack code4lib" at https://gist.github.com/yo-bj/85567f9db773c190b44e4add5e3bc9e0. Feel free to comment! I will also host a breakout session at the conference this week to go over the gist as well as discuss possible restructuring of reporting structures.

**Comment by yo-bj** [comment]
Hi folks - now that there's been some work on expanding the CoC, I'd like to bump this thread as well as the gist in the last comment from 2018. Again, feel free to use as you see fit.

**Comment by phette23** [comment]
I am going to subsume this issue into #90 which highlights the needs for articulated community standards/guidelines. I'll carry over the gist reference since that seems like an excellent starting place.

If anyone thinks there's a missing component that was brought up here that #90 doesn't address, I think the best course of action would be to create a brand new issue and extract the relevant pieces of conversation from here, rather than carry on  here when there's quite a lot going on and it's a little unclear what concerns are still relevant.
