### ISSUE TITLE
To Do - Review CoC for enforcement warning signs

### ISSUE THREAD

**Issue by yo-bj** [code4lib/code-of-conduct#67]
Once #50 has gone through, it might be worthwhile to review the latest version of the CoC using the following list at https://otter.technology/blog/2017/12/28/code-of-conduct-enforcement-warning-signs/, and creating a PR to address any areas that need improvement based on the review.

**Comment by phette23** [comment]
Reading through this blog post, here are my thoughts.

> 1. The email address to send Code of Conduct incident reports to is an info@ or reports@ email address with no indication of who is on the recieving end. Is there an actual person who will answer an emailed report? I’m never sure.

This is true of us. To be honest, I strongly dislike the idea of a personal email being in an official document, especially for an ad hoc community like Code4Lib. It'd be one thing if we had a real org chart where someone was clearly responsible, but our Community Support Coordinators roll over every two years. We do have the [CSS volunteers](https://github.com/code4lib/code-of-conduct/blob/main/css_volunteers.md) doc listing personal contacts but it is out-of-date.

For 4, we have a wide range of consequences articulated under the "[sanctions](https://github.com/code4lib/code-of-conduct/blob/main/code_of_conduct.md#sanctions)" header. I don't want to respond to all 10 items but most clearly do not apply; happy for more opinions on that.

This one phrase from the CoC's "[Conflict Resolution](https://github.com/code4lib/code-of-conduct/blob/main/code_of_conduct.md#conflict-resolution)" section no. 2 stands out to me as problematic:

> If you are on the listserv, you're in a free-for-all for public messages;

This seems like it falls somewhere in the 7-9 range of statements that are dismissive or undermine the purpose of the CoC; it sounds like we are trying to not take responsibility for the listserv's content, which is not the case.

So, in sum, I propose the following revision (retaining the hyperlinks in the original):

"If you are on the listserv, you're in a free-for-all for public messages; however, the listserv does have a maintainer, Eric Lease Morgan. In addition, there are Community Support Volunteers whom you are welcome to involve." => "The Code4Lib listserv is maintained by Eric Lease Morgan. Our Community Support Volunteers monitor its messages and may be contacted via email."

**Comment by phette23** [comment]
Also worth noting with regards to no. 1 from the blog post: we have a track record of responding to every report, which is thoroughly documented and publicized in this repo, so it really doesn't look like a major concern to me.

**Comment by anarchivist** [comment]
Thanks @phette23. I've never liked the "you're in a free-for-all" turn of phrase in the code of conduct, so +1 for phasing it out in preference of the rewrite you propose.
