### ISSUE TITLE
Review for Code4Lib 2021

### ISSUE THREAD

**Issue by jscaffrey** [code4lib/code-of-conduct#85]
The [Website Working Group](https://wiki.code4lib.org/Code4Lib_2021_Conference_Committees#Website_Working_Group) for Code4Lib 2021 is [reviewing content](https://github.com/code4lib/2021.code4lib.org/issues/3) for Code4Lib's first conference virtual conference without an in-person venue.

We will include the Code of Conduct similar to previous years, and suggest the community review, discuss, and revise the Code of Conduct in advance of the virtual meeting.

Relatedly, we'd like to invite the revision to the Photography Policy on the website for the online conference, which we are temporarily hiding until we have a version for the virtual conference:

>Photography Policy
>
>Do not photograph, film, or audio-record anyone at Code4Lib without their expressly-given permission beforehand. Color- 
>and pattern-coded lanyards are available at the registration desk to help indicate the wearer’s preference for photography 
>ONLY. Please note, regardless of lanyards, you must always ask before filming or audio-recording attendees. 

Some potential topics for consideration that came up in our 11/16/2020 discussion were:
- discouraging screenshots of conference participants without their permission
- the ability for participants to turn on and off their video, and whether that is a sufficient replacement for the lanyard
- preferences for their image being shared beyond the conference, like social media (for both attendees and speakers)
- whether recordings of conference sessions will or will not share conference attendees' video (if they are sharing video)

**Comment by phette23** [comment]
I agree this is a good opportunity to review the CoC and make sure it'll meet the needs of a virtual conference. I hope it will, we committed to monitoring online spaces in the past, but I'm still not 100% sure all the language is suitable.

For the photography policy—that's not actually in the CoC, it's just been a conference policy passed down for several years now. But the CSS would be happy to assist in developing a new policy oriented towards a virtual conference. I think the bullet points you outline are great starting points.

**Comment by jscaffrey** [comment]
Adding -- hoping to have reviewed content live mid January, in time for registration opening January 20 (by current timeline).

**Comment by phette23** [comment]
Upon reviewing the **Escalation** section, the specific means of contacting the Community Support Squad (CSS) are not accurate and need to be phrased in a more generic manner that won't need to be updated as modes of communication change over time. Specifically these details:

> If you are at a conference or other event, find the on-call Community Support Volunteer or the event organizer or staff person, who should be listed on the wiki. If you can't find either of these, there will be other staff available to help if the situation calls for immediate action.
> If you are in the #code4lib IRC, the zoia command to list people designated as channel helpers is @helpers . There is at least one helper in the channel at most times.
> If you are in the code4lib Slack, contact one of the admins. You can find this list by clicking the the "⋮" button in the top right and then selecting "Workspace Directory." You can filter the list to show only Admins by using the select list.

We don't really use the wiki anymore but rely on the conference website, so the first paragraph should be phrased generically like "there will be posted, e.g. on a conference website, clear contact information for Community Support". I don't think the zoia `@helpers` are the same as CSS (I'm not on irc, for instance). Finally, Slack admins are not the same as CSS. We will create a Slack group that can be contacted instead, maintain its membership, and reference it in this section of the CSS.

This is just a sketch but I will compose specific edits in a forthcoming PR.

**Comment by phette23** [comment]
I merged my PR addressing this issue today and think this can be provisionally closed, though let me know if there's more work to be done.
